title: XML schemas for ISO/TC 211 Geographic information/Geomatics
title_html: XML&nbsp;schema representations of&nbsp;geographic&nbsp;technology standards

committee:
  id: 211
  name: Geographic information/Geomatics
  home: https://committee.iso.org/home/tc211

footer_nav:
  - url: https://committee.iso.org/home/tc211
    title: Committee Site

resource_listings:
  schemas:
    index_url: 'schemas'
    index_title: "Schemas"
    resource_root: 'schemas'
    resource_label: "schema"

description: >-
  The XML schema repository for geographic information technology
  from ISO/TC 211 Geographic information/Geomatics.

tagline: >-
  XML schema repository for geographic information technology

author: "ISO/TC 211"
email: open.source@ribose.com

theme: jekyll-theme-isotc211

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

markdown: kramdown

source: build_source
include:
  - build_source

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
